REM pstreeselect_interval_partitioning.sql

set echo on
REM spool &&2._pstreeselect&&1._interval_partitioning
spool pstreeselect_interval_partitioning append

ALTER SESSION SET CURRENT_SCHEMA=&&2.;

DROP TABLE &&2..PSYPSTREESELECT&&1. PURGE
/

CREATE TABLE &&2..PSYPSTREESELECT&&1. 
(SELECTOR_NUM   INTEGER NOT NULL,
 TREE_NODE_NUM  INTEGER NOT NULL,
 RANGE_FROM_&&1. VARCHAR2(&&1.) NOT NULL,
 RANGE_TO_&&1.   VARCHAR2(&&1.) NOT NULL) 
PARTITION BY RANGE (selector_num) INTERVAL (1)
(PARTITION VALUES LESS THAN(2))
TABLESPACE "PTWORK" STORAGE(INITIAL 64K NEXT 64K)
/
INSERT INTO &&2..PSYPSTREESELECT&&1. 
      (SELECTOR_NUM,
       TREE_NODE_NUM,
       RANGE_FROM_&&1.,
       RANGE_TO_&&1.)
SELECT SELECTOR_NUM,
       TREE_NODE_NUM,
       RANGE_FROM_&&1.,
       RANGE_TO_&&1.
  FROM &&2..PSTREESELECT&&1.
/

DROP TABLE &&2..PSTREESELECT&&1. PURGE;
/
ALTER TABLE &&2..PSYPSTREESELECT&&1. RENAME TO PSTREESELECT&&1.
/

CREATE UNIQUE  INDEX &&2..PS_PSTREESELECT&&1. ON &&2..PSTREESELECT&&1.
(SELECTOR_NUM
,TREE_NODE_NUM
,RANGE_FROM_&&1.
,RANGE_TO_&&1.) 
local PCTFREE 5 COMPRESS 1 TABLESPACE "PSINDEX" STORAGE(INITIAL 64K NEXT 64K)
/
ALTER INDEX &&2..PS_PSTREESELECT&&1. NOPARALLEL LOGGING
/
CREATE INDEX &&2..PSAPSTREESELECT&&1. ON &&2..PSTREESELECT&&1. 
(SELECTOR_NUM
,RANGE_FROM_&&1.
,RANGE_TO_&&1.
,TREE_NODE_NUM) 
local PCTFREE 5 COMPRESS 1 TABLESPACE "PSINDEX" STORAGE(INITIAL 64K NEXT 64K)
/
ALTER INDEX &&2..PSAPSTREESELECT&&1. NOPARALLEL LOGGING
/

--add your own roles here
GRANT SELECT ON &&2..pstreeselect&&1. TO sysadm;
GRANT SELECT ON &&2..pstreeselect&&1. TO ps_read_all_role;
GRANT SELECT ON &&2..pstreeselect&&1. TO ace_read_only;
GRANT SELECT ON &&2..pstreeselect&&1. TO psteam;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&2..pstreeselect&&1. TO ace_read_write;

spool off