REM pstreeselnum.sql
spool pstreeselnum append

set echo on
REM spool &&1._pstreeselnum

ALTER SESSION SET CURRENT_SCHEMA=&&1.;

ALTER USER &&1. quota UNLIMITED on PTTREE;

DROP TABLE &&1..PSYPSTREESELNUM PURGE
/

CREATE TABLE &&1..PSYPSTREESELNUM 
(SELECTOR_NUM INTEGER NOT NULL) 
TABLESPACE PTTREE STORAGE(INITIAL 64K NEXT 64K)
NOPARALLEL
/
INSERT INTO &&1..PSYPSTREESELNUM (SELECTOR_NUM)
SELECT SELECTOR_NUM FROM &&1..PSTREESELNUM
/
INSERT INTO &&1..PSYPSTREESELNUM (SELECTOR_NUM)
SELECT 0 FROM DUAL WHERE NOT EXISTS (SELECT * FROM &&1..PSYPSTREESELNUM)
/
DROP TABLE &&1..PSTREESELNUM PURGE;
/
ALTER TABLE &&1..PSYPSTREESELNUM RENAME TO PSTREESELNUM
/

--add your own roles here
GRANT SELECT, INSERT, UPDATE, DELETE ON &&1..PSTREESELNUM TO sysadm;
GRANT SELECT ON &&1..PSTREESELNUM TO ps_read_all_role;
GRANT SELECT ON &&1..PSTREESELNUM TO psteam;

spool off